#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

export PATH="/opt/homebrew/bin:/opt/homebrew/sbin:$PATH"
export PATH="/opt/homebrew/opt/node@16/bin:$PATH"
export PATH="$HOME/.yarn/bin:$PATH"

pnpm exec commitlint --edit $1